@echo off

SET "ROUTES=%LEADERBOARD_ROOT%\data\routes_1s.xml"
SET "REPETITIONS=1"
SET "DEBUG_CHALLENGE=2"
SET "TEAM_AGENT=%LEADERBOARD_ROOT%\leaderboard\autoagents\human_agent.py"
SET "CHECKPOINT_ENDPOINT=%LEADERBOARD_ROOT%\results.json"
SET "CHALLENGE_TRACK_CODENAME=SENSORS"
SET "OBJECT_DETECTED=%LEADERBOARD_ROOT%\objects_detected.txt"
SET "AUDIO_FOLDER=%LEADERBOARD_ROOT%\audio\\"
SET "ASSISTANT=1"

CALL ./scripts/run_evaluation.bat
pause